### ISSUE TITLE
Add a 'shell' command with history and autocomplete support.

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#106]
Add a 'shell' command (will replace 'prompt') that supports history (with <arrow up>) and context sensitive autocomplete. Use the jline3 library.

**Comment by PEZ** [comment]
Have you considered making this the default for the `poly` command? So it would drop you in to the shell instead of complaining:

```
  Unknown command ''. Type 'poly help' for help.
```

**Comment by tengstrand** [comment]
I guess you mean if you type just "poly" then it should automatically start a shell,
but if you type something like "poly x" then the existing error message could be shown.

I like the idea and I think that is a good default and it will help people getting started!

When the new shell is in place, you will get so much speed and support from it that I believe
this will be the standard way of interacting with the tool.

Good input, and thanks @PEZ !

**Comment by PEZ** [comment]
Yes that's exactly what I mean. 😄

**Comment by imrekoszo** [comment]
I was able to get command history using `clj -Tpoly shell` - clj has that built in.

**Comment by tengstrand** [comment]
Okay cool. The new `shell` command will also support autocomplete and knows which arguments are relevant for each command + can autocomplete bricks, projects, dirs/files, etcetera.
