### ISSUE TITLE
Update or remove commands doc in repo

### ISSUE THREAD

**Issue by bpringe** [polyfy/polylith#112]
**Is your feature request related to a problem? Please describe.**

This is related to a potential documentation issue.

**Describe the solution you'd like**

Update the command documentation to replace the mentioned usage of `ns-to-lib` with a description of how lib usage is calculated now.

This error description is the content I'm talking about (see [here](https://github.com/polyfy/polylith/blob/master/doc/commands.md#check)):

> Error 109 - Missing libraries in project.
    Triggered if a project doesn't contain a library that is used by one
    of its bricks. Library usage for a brick is calculated using :ns-to-lib in
    './deps.edn' for all its namespaces.
    
Isn't that the old way of calculating lib usage?

**Comment by bpringe** [comment]
I'm realizing other command docs there are outdated as well when compared with the tool's output (at least I saw this with the `info` command). So, I'm guessing that whole doc is based on help output from an earlier version of the tool.

I'm wondering if you think it's a good idea to keep that doc around, considering it may repeatedly become outdated as the tool evolves, or instead have users refer to the help output for the commands entirely for information about them?

**Comment by tengstrand** [comment]
Looks like I have missed to update the documentation!
The solution must be to generate this documentation from the output of the different commands, so that this will not happen again!
Thanks for reporting this. It's important that you can trust the documentation.

**Comment by tengstrand** [comment]
The documentation is now auto-generated from the output of the real commands. The documentation has been updated in the [latest release](https://github.com/polyfy/polylith/releases/tag/v0.2.12-alpha). This was a good fix, and will keep the documentation in sync from now!

**Comment by bpringe** [comment]
Awesome!
