### ISSUE TITLE
Support "tools" installation and use

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#114]
**Is your feature request related to a problem? Please describe.**
Now that Clojure CLI 1.10.3.933 is out, it would be very convenient to be able to install `poly` as a "global" tool using the CLI's standard machinery and then use it (via the CLI) in any project: `clojure -Ttools install ...` and then `clojure -Tpoly ...`

**Describe the solution you'd like**
Add a new namespace to the `poly` CLI with a `.api` suffix (this is a de facto standard for "tools") that contains high-level "exec" functions that can be invoked via `clojure -Tpoly <fn> <kvs-args>` and map those functions (and arguments) to `poly`'s internal command/argument structure as appropriate.

**Describe alternatives you've considered**
A wrapper could be written in user space, but it would be nice to have this baked into the tool.

**Comment by tengstrand** [comment]
Merged to `master`. Thanks again for this contribution @seancorfield!

**Comment by tengstrand** [comment]
This has been [released](https://github.com/polyfy/polylith/releases/tag/v0.2.12-alpha) now. My plan is to support both the normal "poly style" and "CLI tools style" when I start working on the auto-complete in the new `shell` command, issue #106, and I think that can be really cool!
