### ISSUE TITLE
Add support for running specific brick tests

### ISSUE THREAD

**Issue by cyppan** [polyfy/polylith#116]
**Is your feature request related to a problem? Please describe.**

At my company we have migrated our different "micro-services" into a single Polylith codebase (bases and components), but our (historical) tests are not optimized for speed, and it's a bit problematic when you use the polylith test runner because it will run all the bricks tests (even if you can run only those modified since the last release or the last stable, it's still very long, up to 5 minutes per base for us).

**Describe the solution you'd like**

I would like to be able to poly test specific bricks with either `poly test base:my-base`, `poly test component:my-component` or `poly test brick:my-component`. 
By default it would run those from the context of the development project.

**Describe alternatives you've considered**

AFAIU The recommended way to handle slow tests is to move them into projects, but we've been bad with our tests, a lot of them are slow, so I've started optimizing tests speed, it's a lot of work.

**Comment by tengstrand** [comment]
Hi @cyppan!

I've had the same idea for a while, but wasn't sure if it was going to be used or not. Now when you have this need, it makes perfectly sense to support it.

We use `bricks` already, so it will be implemented like this, e.g.: `poly test brick:c1:c2:b1`.

I also had an idea of introducing the view concept, see discussion #118, which is related to this. Feel free to add comments on that!

**Comment by cyppan** [comment]
it would be great! 👌🏻

**Comment by tengstrand** [comment]
This has now been fixed and [released](https://github.com/polyfy/polylith/releases/tag/v0.2.12-alpha), so please check it out!
