### ISSUE TITLE
Move the poly documentation to gitbook

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#128]
**Is your feature request related to a problem? Please describe.**
The current documentation is hard to use because everything lives into one huge document.

**Describe the solution you'd like**
Move the documentation to gitbook, where it can be split up in sections and be easier to use.

**Comment by furkan3ayraktar** [comment]
The documentation is on [Gitbook](https://polylith.gitbook.io/poly) and ready to be reviewed.
