### ISSUE TITLE
Ignore top-level 'data_readers.clj'

### ISSUE THREAD

**Issue by Matthew-Ielusic** [polyfy/polylith#129]
**Is your feature request related to a problem? Please describe.**
Reader tags are declared in 'data_readers.clj' files on the classpath root.  If a brick needs reader tags, it would be natural to place them in its src folder, or perhaps in resources, but 'poly check' issues a spurious Warning 205: Non top namespace.

**Describe the solution you'd like**
The polylith tool should ignore 'data_readers.clj' files when checking for non-top namespaces.

**Describe alternatives you've considered**
Moving the file inside the top-level namespace suppresses the warning, but then Clojure cannot find the file, because it only looks in the classpath root.

**Comment by seancorfield** [comment]
As noted on Slack: `data_readers.clj` and `data_readers.cljc` are both valid -- but `data-readers` is the namespace in both cases.

**Comment by furkan3ayraktar** [comment]
It seems like `data_readers` are used as resources not sources, even though they have `.clj`/`.cljc` extension. So, it might be a better to place them under a bricks or a projects resources folder.

However, it also seems like Polylith treat the `.cljc` and `.clj` files as sources, even though they are under resources folder. This should not be the case in my opinion and Polylith should not treat files under resources as sources.

**Comment by tengstrand** [comment]
When I tested this and put `data_reader.clj` directly under the `src` root, in e.g. `bases/poly-cli/src`, I get this error:
```
clojure.lang.ExceptionInfo: Not a valid data-reader map {:url #object[java.net.URL 0x71812481 "file:/Users/joakimtengstrand/source/polylith/bases/poly-cli/src/data_readers.clj"]}
```
But when I put it under e.g. `bases/poly-cli/src/testing` it works.

**Comment by seancorfield** [comment]
If Clojure thinks it's invalid in the root place and you don't get the exception when it isn't in the root place, that's because Clojure is not actually reading the file -- so you have the wrong format.

It is supposed to be a hash map from qualified symbols to qualified symbols. The keys are reader tags and the values and functions to read the data. See this example in the clj-time project: https://github.com/clj-time/clj-time/blob/master/src/data_readers.clj

**Comment by tengstrand** [comment]
This should be fixed now in the branch `issue-129-ignore-data-readers` which you can try out @Matthew-Ielusic. I would prefer to wait with releasing this, till we have more functionality. In the meantime, you can either live with this warning or use the hash in the branch. Hope that works for you!

**Comment by Matthew-Ielusic** [comment]
I tried it out on my personal Windows laptop, and it seems to be working!

**Comment by tengstrand** [comment]
Nice!
