### ISSUE TITLE
Symbolic links to non-existing source code files throws an exception

### ISSUE THREAD

**Issue by olymk2** [polyfy/polylith#138]
**Describe the bug**
poly create c name:products  fails if you have temporary files in you project structure

 :cause /workspace/components/middleware/src/com/example/middleware/.#core.clj (No such file or directory)

**To Reproduce**
1. create a file in an existing component with a .# in front of the name 
2. poly create c name:products
3. See error

**Expected behavior**
A new component sholul be created, editor temporary files should not get in the way

**Operating System (please complete the following information):**
 - OS: Linux / Solus
 - Version: solus 4.1

**Versions (please complete the following information):**
 - Java: openjdk 11.0.10 2021-01-19
 - Poly: 0.2.12-alpha (2021-08-28)

**Comment by tengstrand** [comment]
Hi Oliver!

I haven't managed to reproduce your problem, but I have a few questions.

1. Can you execute all other commands, except `create component`? 
2. If you execute `poly ws get:components:middleware:namespaces:src` does it include the `.#core.clj` namespace?
3. Does the file contain normal Clojure code or something else?

I can ask @furkan3ayraktar to see if he can reproduce the problem.

**Comment by olymk2** [comment]
Okay seems even poly info fails, so yes all commands likley fail, step 2 also fails with the same error.
So after inspecting a bit more I noticed that the tmp file is actually a symlink.

I did a quick search and found this https://stackoverflow.com/questions/5738170/why-does-emacs-create-temporary-symbolic-links-for-modified-files which has a bit of info, interestingly when I check the symlink does not actually exist on my system, these are usually cleaned up when you save the buffer of the file in question

.#foo.c -> user@host.12345:1296583136

Hope this helps I guess its the fact its a symlink causing the issue.

**Comment by tengstrand** [comment]
Hi @olymk2!

I could reproduce the problem and I have changed the heading in this issue to reflect that.

Please change the `:sha` in the `:poly` alias in your `./deps.edn` file to `17c3e3aa48ecec06966d4f8f0200a119bf0bd034`and verify that it works by executing something like `clojure -M:poly check` and report back if it works for you too!

**Comment by olymk2** [comment]
Grand that seems to have resolved the issue thanks i can now run poly info with out hitting the exception.

**Comment by tengstrand** [comment]
Okay, cool!
