### ISSUE TITLE
poly flags :dev alias if it has no :extra-paths in it

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#144]
**Describe the bug**
If you're only using `:extra-deps` in `:dev` with `:local/root` dependencies on bricks, `poly` complains:

```
Error in ./deps.edn: {:aliases {:dev {:extra-paths ["missing required key"]}}}
```

You can add `:extra-paths []` to satisfy it. That feels like legacy behavior?

**Comment by tengstrand** [comment]
Yes, this is not the behaviour we want.

**Comment by volisoft** [comment]
Just to piggy back on this ticket: even though deps allows keywords in top-level `:paths`, poly expects only strings with error:
```
Couldn't read the 'deps.edn' file from project 'test-project': {:paths [["should be a string"]]}
```
