### ISSUE TITLE
Several clojure -T:build uberjar commands incorrectly contain -A:deps

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#149]
**Describe the bug**

`example/doc-example/build.clj` has:

```clojure
(ns build
  "The build script for the example of the poly documentation.

   Targets:
   * uberjar :project PROJECT
     - creates an uberjar for the given project

   For help, run:
     clojure -A:deps -T:build help/doc

   Create uberjar for command-line:
     clojure -A:deps -T:build uberjar :project command-line"
```

Although `-A:deps` is fairly harmless here, it is not required and should be removed. There are five occurrences of `-A:deps` with `uberjar` in three files.

Note that `-A:deps` **is** required for the `help/doc` command:

```bash
clojure -A:deps -T:build help/doc
```

But that is the only place it is needed.

I have not checked the GitBook to see if it occurs elsewhere in that source (I don't know the URL to look at the source for that).

**Comment by tengstrand** [comment]
I made you an editor of the GitBook documentation @seancorfield, so feel free to fix this and other mistakes if you find any!

**Comment by seancorfield** [comment]
Thank you! I just got the invite and accepted it. I'll try to spend some time learning about GitBook over the next few days! :)

**Comment by tengstrand** [comment]
I've merged your changes. Thanks!
