### ISSUE TITLE
Homebrew warning

### ISSUE THREAD

**Issue by robert-stuttaford** [polyfy/polylith#159]
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the polyfy/polylith tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/polyfy/homebrew-polylith/Formula/poly.rb:8

**Comment by furkan3ayraktar** [comment]
Removed `bottle :unneeded` line from the Formula templates [here](https://github.com/polyfy/homebrew-polylith/pull/1). Starting from the next version we release, this warning should disappear.
