### ISSUE TITLE
If test setup fails, tests should not run

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#161]
**Describe the bug**
If per-project test setup fails (throws an exception), `poly test` still runs the tests (which may or may not fail).

**To Reproduce**
Have a per-project test setup that throws an exception, and at least one test that will run from that project. The test setup will fail but the tests will still be run (and so will the test teardown).

**Expected behavior**
If the per-project test setup fails, tests should not run and `poly test` should report the failure (with a stacktrace).

I'm not sure whether test teardown should be run if setup fails -- my initial feeling is that if test setup fails, neither the tests nor the teardown should be run.

This is kind of the flip-side to the previous bug I raised around per-project fixtures (where teardown was **not** being run if tests failed -- here tests should not be run if _setup_ fails).

**Comment by tengstrand** [comment]
Fixed and pushed to `master`, but not released yet.

**Comment by seancorfield** [comment]
You've removed the `try`/`finally` that ensures tear down runs even if tests fail -- which reintroduces a bug I raised a while back (that you fixed by adding that `try`/`finally`).

**Comment by tengstrand** [comment]
I've merged a fix to master. Hopefully it will work this time.

**Comment by seancorfield** [comment]
Thank you. That looks correct now.
