### ISSUE TITLE
Update djblue/portal to 0.18.1

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#166]
Portal has had a lot of updates since 0.15.1 which is the version Polylith currently uses.

I'd actually forgotten that `poly` includes Portal until I started seeing this warning when running `poly test`:

```
WARNING: random-uuid already refers to: #'clojure.core/random-uuid in namespace: portal.runtime.browser, being replaced by: #'portal.runtime.browser/random-uuid
```

That's a conflict between the old Portal and Clojure 1.11 Alpha 3 which we're running at work. That has been addressed in more recent versions of Portal.

**Comment by tengstrand** [comment]
Merged into master. I also updated the other libraries.
