### ISSUE TITLE
git deps with implicit url do not work

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#174]
**Describe the bug**
tools.deps.alpha supports git deps like io.github.seancorfield/deps-new {:git/sha "..."} (plus com.github.user/repo and a few others), but poly test does not. See https://github.com/clojure/tools.deps.alpha/blob/master/src/main/clojure/clojure/tools/deps/alpha/extensions/git.clj#L17-L33

**To Reproduce**

https://github.com/seancorfield/poly-issue-174

**Expected behavior**
The git deps should work, just like t.d.a.

**Comment by tengstrand** [comment]
I have pushed a fix, so please have a look at the [issue-174](https://github.com/polyfy/polylith/tree/issue-174) branch @seancorfield.

**Comment by seancorfield** [comment]
This seems to work as expected. Thank you!

**Comment by tengstrand** [comment]
Thanks for verifying this. Now it's merged to the `master` branch.
