### ISSUE TITLE
Poly test does not give non-zero exit code when check fails

### ISSUE THREAD

**Issue by svdo** [polyfy/polylith#177]
**Describe the bug**
When running `poly test`, before running the tests it will also run the `check` command. If that fails, poly shows the messages and exits. The exit code however is zero, meaning that it claims that everything is OK. This is especially harmful in CI because it causes that the build succeeds while the tests are not even run.

**To Reproduce**

1. Create an error in a polylith project; for example create a circular dependency or remove a required component from a project.
2. In a bash-compatible shell, run `poly check; echo "Exit code: $?"` and notice that the error is printed correctly, and the exit code is `1` as expected.
3. Now run `poly test; echo "Exit code: $?"` and notice that, while the error is printed, the exit code is `0`.

Please note that the same happens when running `clojure -M:poly` instead of running poly from Homebrew.

**Expected behavior**
The error code should have been 1.

**Operating System (please complete the following information):**
 - OS: macOS
 - Version: 11.6.2

**Versions (please complete the following information):**
 - Java: openjdk version "17.0.1" 2021-10-19
 - Poly: 0.2.13-alpha (2021-10-12)
 - Brew: 3.3.9-80-g26694fd

**Comment by tengstrand** [comment]
Hi! 

Thanks for reporting this. I will have a look at this soon.

/Joakim
