### ISSUE TITLE
Remove security warning

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#181]
We have this warning in GitHub:
![image](https://user-images.githubusercontent.com/631272/154200971-491d0aaf-b130-40ea-889b-612141b06024.png)

The pom.xml has never been used by the code and was deleted earlier.

Investigate how to get rid of this warning in the best way.

**Comment by furkan3ayraktar** [comment]
These were triggered by an unnecessary `pom.xml` that got pushed and deleted in the past. I dismissed those alerts now.
