### ISSUE TITLE
Support running all tests for selected projects

### ISSUE THREAD

**Issue by miikka** [polyfy/polylith#189]
**Is your feature request related to a problem? Please describe.**

Sometimes I'd like to run tests for a project that has not changed. Right now we're migrating a large number of services to Polylith and we've had trouble with making sure that integration tests pass in all environments. Being able to run the tests for a project without any changes is an essential sanity check.

**Describe the solution you'd like**

I'd like to have a command-line flag for `poly test project:foo` that runs the tests for the project even if the project has not change, e.g. `poly test :all project:foo`.

**Describe alternatives you've considered**

1. `poly test :all` runs literally all tests, which is great but slow if you have a large test suite.
2. If you tag the initial commit of the repo with `git tag always ...`, then you can use `poly test project:foo since:always`
3. If you do a dummy edit to the project, then the tests are run, of course.

**Comment by tengstrand** [comment]
Today the code runs all test for all projects if we type `poly test :all`. I agree it's a more resonable behaviour to run all tests for selected project(s) if we type `poly test :all project:foo` or `poly test :all project:foo:bar`.

**Comment by tengstrand** [comment]
It would be cool if you could test the functionality in the [issue 189](https://github.com/polyfy/polylith/tree/issue-189) branch @miikka.

**Comment by miikka** [comment]
Tried out commit 989c05703e34484c4acf275c54399221a079b680 and it seems good. `poly test :all project:my-project` now does what I was hoping for.

**Comment by tengstrand** [comment]
Okay cool. It should work for other variants also, like `poly test project:my-project` or `poly test :project :project:my-project`.
