### ISSUE TITLE
brew poly formula looks broken (at least on my mac)

### ISSUE THREAD

**Issue by cyppan** [polyfy/polylith#190]
**Describe the bug**
I installed the polylith tool via brew previously (0.2.13-alpha) and I can't update it now (or even brew info it)

**To Reproduce**
```
brew update polyfy/polylith/poly
Error: polyfy/polylith/poly: Calling bottle :unneeded is disabled! There is no replacement.
Please report this issue to the polyfy/polylith tap (not Homebrew/brew or Homebrew/core):
  /opt/homebrew/Library/Taps/polyfy/homebrew-polylith/Formula/poly.rb:8
```
**Operating System:**
 - OS: MacOS
 - Version: 12.1

**Versions:**
 - Java: openjdk version "17.0.2" 2022-01-18
 - Poly: 0.2.13-alpha (2021-10-12)
 - Brew: 3.4.1

**Comment by edannenberg** [comment]
See https://github.com/polyfy/homebrew-polylith/pull/2 for a workaround

**Comment by furkan3ayraktar** [comment]
I've merged https://github.com/polyfy/homebrew-polylith/pull/2 now which should solve the issue.
