### ISSUE TITLE
Use source paths from deps.edn files

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#206]
Don't read read source code from hard coded paths, see this [example](https://github.com/polyfy/polylith/blob/master/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L152) (thanks @imrekoszo for pointing this out!).

Instead, use the paths in the `deps.edn` files.

Make sure we support more than one src or test directory (because it's supported by tools.deps).

**Comment by imrekoszo** [comment]
Thanks for creating the issue! Let me try and add some extra thoughts.

The main area I would add more checks around is paths included in the development project and profiles vs _entities_ (bricks+projects) available in the workspace.

1. every entity that has sources or tests should be included in at least one profile or the development project
2. when an entity is included in the dev project or a profile, all of its source and test paths should be included (check top-level deps.edn vs entity deps.edn)
3. top-level deps.edn should not refer to any entity paths that are not present in the entity's own deps.edn

Also with regards to

> has a `test` directory, but it's not defined in its `deps.edn` file

this might trigger false positives (`doc` or `examples` etc. directories next to the entity deps.edn) so I'd keep the list of checked directory names short (src, test, resources) _and_ configurable in workspace.edn.

**Comment by imrekoszo** [comment]
Here are the relevant locations in code where I found these hardcoded:

- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/workspace-clj/src/polylith/clj/core/workspace_clj/bases_from_disk.clj#L11-L12
- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/workspace-clj/src/polylith/clj/core/workspace_clj/components_from_disk.clj#L13-L14
- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L151

The following are perhaps less relevant but still need checking:

- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/interface/criterias.clj#L35-L42
- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/profile_src_splitter.clj#L5
- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/sources_on_disk.clj#L6

Ideally, the question "what are the source/test paths for an entity?" (where entity is either a project or a brick) should be answered based on the info in their deps.edns.

**Comment by tengstrand** [comment]
As Imre pointed out, the brick paths are hard coded and read from disk from `bases_from_disk` and `components_from_disk`. What we instead should do here is to extract the source paths from `base-dir/deps.edn` and `component-dir/deps.edn` by looking in `:paths` and `:aliases > :test > :extra-paths`. 

The next problem is this line:
https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L151

Here we should use the `src-paths` and `test-paths` variables instead when reading the namespaces.

----------

This line:
https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/profile_src_splitter.clj#L5

Instead we need to check all brick and project paths (stored in the workspace structure) to check if they are src and/or test paths. 

It would be good if we introduced a validation (109) that checks that all these paths are valid.

---------

The `resources` directory needs to be named resources, to distinguish it from other src directories.

I have probably forgotten something, but this could be a good start.

**Comment by nkabir** [comment]
I haven't tackled profiles yet and I understand my solution is a bit hacky. It seems to work. I want to share the changes to see if I'm on the right track.

I [changed](https://github.com/rkx-forks/polylith/blob/2de0f76096a3155c93b7520eb6c822fe1857233f/components/workspace-clj/src/polylith/clj/core/workspace_clj/namespaces_from_disk.clj#L114) the `namespaces-from-disk` method to ignore the hard-coded values if there is a `deps.edn` file.

I made similar [changes](https://github.com/rkx-forks/polylith/blob/f068545212f55219d1ff1d43717070fbddc0d374/components/workspace-clj/src/polylith/clj/core/workspace_clj/non_top_namespace.clj#L25) to check `non-top-namespace`.

For [ends-width](https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/profile_src_splitter.clj#L5) can we use `contains`?

**Comment by tengstrand** [comment]
Hi @nkabir!

Yes, a bit hacky and that is also not how we need to approach the problem. Here is my suggestion.

The value for the `:paths` key is calculated here for components:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/components_from_disk.clj#L26
...and the here for bases:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/bases_from_disk.clj#L20

You need to calculate these values first (e.g. as the first let statement at line 12) and then use the `:paths` value instead of the hard coded values we have today:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/components_from_disk.clj#L12-L14
...and you need to do the same for bases:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/bases_from_disk.clj#L10-L12

The next thing we need to approach differently are these two functions :
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/path-finder/src/polylith/clj/core/path_finder/profile_src_splitter.clj#L4-L8

Here we need to compare with all component, base and project paths specified in their `:paths` to know if it is a test or src path. One way of doing it is to collect all src patch for bricks and projects in a set and pass it in as an argument (and the same for test paths) but that is an implementation detail.

My suggestion is that we hard code the `resources` directory to be able to distinguish it from the other kind of paths, which means we can leave this line as it is (if someone can't find a downside with that):
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/path-finder/src/polylith/clj/core/path_finder/interface/criterias.clj#L41-L42

When it comes to reading projects. This line:
https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L151
...should use the value of `src-paths` from here:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L142
...and `test-paths` from here:
https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/projects_from_disk.clj#L144

Finally, in this function:
- https://github.com/polyfy/polylith/blob/abd20bb656e2cdd712732d80e1238316d3ea1b7f/components/path-finder/src/polylith/clj/core/path_finder/sources_on_disk.clj#L6
...we could pass in that set of `:paths` that was gathered from all brick's and project's `deps.edn` files that we mention earlier.

Hope this helps!

**Comment by nkabir** [comment]
Thank you, @tengstrand 
This gives me a better understanding of the scope of necessary changes. I'll try again!

**Comment by nkabir** [comment]
This looks problematic if we use a collection of paths instead of one path. It appears to pluck the first 

https://github.com/polyfy/polylith/blob/22e07082d9d803e28498af8c4eaf048d3d0d5bf8/components/workspace-clj/src/polylith/clj/core/workspace_clj/components_from_disk.clj#L15=

With multiple src directories, we'd need to loop through each one to find an interface file and then return the path that contains `interface.clj` (or `<interface-ns>.clj`)

**Comment by tengstrand** [comment]
Yes, we we need to loop through all sources. I think we should only allow that each interface namespace exists once, and that we need to add a validation that checks this.

**Comment by nkabir** [comment]
A pull request based on suggestions from @tengstrand
There is still work to do. For example, I assume paths contain src, test, and resources.
However, I'm still new to the codebase so I thought it may be helpful for others to see the changes and provide feedback.

https://github.com/polyfy/polylith/pull/220

**Comment by tengstrand** [comment]
Hi @nkabir.

I really appreciate that you want to help out with this, but I feel that this task is a bit too hard for you to start with, and that it takes too much time for me to guide you, which is time that I unfortunately don't have right now.

What I instead suggest is that I implement it, and that I walk you through the solution afterwards. 

If you find something smaller, feel free to give it a try!

/Joakim

**Comment by nkabir** [comment]
No worries, @tengstrand 

It was definitely more extensive than I anticipated. In the meantime, I'll combine clj,cljc,cljs in the same src tree. My motivation was to integrate kit-clj with a Polylith project. I may be able to accomplish that by modifying the kit-clj deps.edn to follow the Polylith convention.

Thanks for your help!

**Comment by tengstrand** [comment]
Okay, cool and thanks for engaging in Polylith!

**Comment by tengstrand** [comment]
I have implemented this, together with issue #217 in the branch `issue-206`, see PR #224. I decided not to add a validation that restricts the names of `src` or `test` paths (as I first suggested). Please check it out, before I merge this to master @nkabir and @imrekoszo.

**Comment by tengstrand** [comment]
I will add support for [aliases](https://clojure.org/reference/deps_and_cli#_paths) in this branch also.

**Comment by imrekoszo** [comment]
@tengstrand thank you, checking!

**Comment by tengstrand** [comment]
I forgot to support aliases, so I created issue #230!
