### ISSUE TITLE
Poly tool should check deps.edn for src and test path

### ISSUE THREAD

**Issue by nkabir** [polyfy/polylith#217]
**Describe the bug**
The poly tool currently assumes all source is under `src` and `test`. Changing `deps.edn` for a component does not affect this. This is unexpected behavior that leads to developer confusion.

**To Reproduce**
1. Create a component
2. Edit `deps.edn` to change `src` path to `src/clj`
3. See warning from `poly check` indicating that `clj.se` namespace is non-root

**Expected behavior**
Poly tool should use `deps.edn` and find source under `src/clj` rather than include `clj` in namespace.

**Comment by nkabir** [comment]
This bug is related to "Use source paths from deps.edn files #206"

**Comment by tengstrand** [comment]
Related to #206

**Comment by tengstrand** [comment]
A fix has been merged to master. Please check it out @nkabir!
