### ISSUE TITLE
In shell mode, CTRL-C should abort the running command in poly, not poly itself

### ISSUE THREAD

**Issue by svdo** [polyfy/polylith#222]
**Describe the bug**
When you're running poly in shell mode (i.e. just run `poly`) and then inside the poly shell a command (e.g. `test :dev`), pressing CTRL-C should abort the test, not the poly shell.

**To Reproduce**
1. Run `poly`
2. Inside the Poly shell, run `test :dev`
3. While the tests are running, press CTRL-C
4. Observe that `poly` is aborted and you have to restart the Poly shell.

**Expected behavior**
The test should be aborted and the user should come back in the poly shell. When no command is running in the poly shell, CTRL-C should be ignored (since CTRL-D is the normal way to exit).

**Operating System (please complete the following information):**
 - OS: macOS
 - Version: any

**Versions (please complete the following information):**
 - Java: openjdk version "18" 2022-03-22
 - Poly: 0.2.14-alpha
 - Brew: 3.3.9-80-g26694fd

**Comment by tengstrand** [comment]
I've implemented this in branch [issue-222](https://github.com/polyfy/polylith/tree/issue-222). 
Please have a look and see if it seems to works @svdo!

**Comment by svdo** [comment]
Thanks! I'll try when I'm back at work and let you know!

**Comment by tengstrand** [comment]
This is merged to master now!!

**Comment by svdo** [comment]
Seems to work nicely, thanks a lot @tengstrand!!

**Comment by seancorfield** [comment]
This doesn't work if the code is in a tight loop and cannot be interrupted between tests -- to me, this fix is worse than the original problem because you can't interrupt a runaway test at all now and you have to find and kill the `poly` process manual.

If you get a second ^C after setting the flag to stop the execution, you should just abort in my opinion.

**Comment by svdo** [comment]
Yes, a second ctrl-c to abort is a common pattern and seems useful to me. It would be nice if it could still abort into the poly shell if possible, but having to wait is indeed not always desirable.

**Comment by tengstrand** [comment]
Okay, then I have to have a new look at it.

**Comment by tengstrand** [comment]
I want to roll back this change for now, and only implement if we can find a better solution in the future (I was never super happy with it, because of that delay, and I haven't found a better solution).
