### ISSUE TITLE
Documentation improvement

### ISSUE THREAD

**Issue by slifin** [polyfy/polylith#225]
On the page https://polylith.gitbook.io/poly/install/install/install-on-linux

The version found in the first bullet point 

```
Download the [latest release](https://github.com/polyfy/polylith/releases/latest) of the poly jar,
e.g. poly-0.2.14-alpha.jar.
```

Does not match the version (2.14-alpha) found later on the same page 

```
#!/bin/sh

ARGS=""
while [ "$1" != "" ] ; do
 ARGS="$ARGS $1"
 shift
done

exec "/usr/bin/java" $JVM_OPTS "-jar" "/usr/local/polylith/poly-0.2.13-alpha.jar" $ARGS
```

**Comment by tengstrand** [comment]
I have updated the documentation. Thanks for pointing this out!
