### ISSUE TITLE
Support XDG systems properly for config.edn file

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#227]
**Is your feature request related to a problem? Please describe.**

On XDG systems, the convention is to put user-level config in directories under `$XDG_CONFIG_HOME/` (typically `$HOME/config/`) so Polylith's `config.edn` should be in `$XDG_CONFIG_HOME/polylith/config.edn` instead of `$HOME/.polylith/config.edn`.

**Describe the solution you'd like**

Polylith should detect the `XDG_CONFIG_HOME` environment variable and use the appropriate path on such systems, but continue to use the other location when `XDG_CONFIG_HOME` is not set.

To avoid backward compatibility issues, Polylith should auto-migrate the current `config.edn` to the correct location on XDG systems and replace the old `config.edn` contents with a comment indicating the new location.

Specifically:
* on a non-XDG system, continue to use `$HOME/.polylith/config.edn` as currently (creating it if missing)
* on an XDG system:
  * if `$XDG_CONFIG_HOME/polylith/config.edn` does not exist,
    * if `$HOME/.polylith/config.edn` exists
      * copy it to the XDG location, then replace the old content with a comment indicating the XDG location
    * if `$HOME/.polylith/config.edn` does not exist
      * create the XDG config with the default content
      * perhaps also create `$HOME/.polylith/config.edn` with a comment indicating the XDG location? @imrekoszo cautioned that XDG systems are about not cluttering up the `$HOME` directory!
  * use `$XDG_CONFIG_HOME/polylith/config.edn`

**Describe alternatives you've considered**

1. Leave the behavior as it is -- XDG users may continue to complain that Polylith does not follow conventions.
2. Use/create `config.edn` in the XDG location and ignore any old file under `$HOME/.polylith` -- XDG users might still edit the non-XDG file (e.g., if they're following an outdated blog post) and wonder why their changes don't work; this could also be a breaking change for users that have already configured Polylith using the "old" `config.edn` since their changes would stop working when they upgraded `poly` and it created a new, default XDG `config.edn` file.

**Additional context**

Polylith's own CI assumes the `$HOME/.polylith/config.edn` location. If `poly` auto-migrates on XDG systems, this setup does not need to change even if the CI system is XDG.

Polylith calculates the path to `config.edn` in many locations in the code. This should all be centralized into a single `component` (and some of the existing functionality in `components/command` migrated to this new component).

**Comment by seancorfield** [comment]
The `polylith.clj.core.user-config.core` ns seems like the right place for all of this to happen and then for everything else to use this `component` as the standardized way to get the location (or content) of the user configuration.

Some test code (and some test files) also reference this path -- and in some places do so with this hardcoded path:

```
/Users/joakimtengstrand/.polylith/config.edn
```

The steps, as I see them:
1. refactoring the code to lift the path calculation out of `config-content` (which is private) into a publicly-callable `config-file-path` function
2. update all code that calculates that path to call that function instead (and make sure file reads are refactored down into this component!)
3. add `xdg-config-dir` function which will return `nil` on non-XDG systems or the path from the `$XDG_CONFIG_HOME` environment variable (not sure if this needs to be in the interface or not yet)
4. refactor `config-file-path` -- essentially rename it to `user-config-dir` and make it private (non-XDG) and have the new public `config-file-path` return the path conditionally
5. for the migration, update`polylith.clj.core.command.user-config` to check for XDG and copy old to new if needed (and update old)

**Comment by seancorfield** [comment]
Looking at the XDG spec https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html (thanks @imrekoszo ), it seems that there's no need for any XDG environment variables to be set, so there's no way to decide one system is following XDG conventions and another is not -- so it would probably be better for the `poly` tool to just shift to following the XDG conventions regardless, using `~/.config/polylith/config.edn` by default or `$XDG_CONFIG_HOME/polylith/config.edn` if that env var is set -- and migrating the old `~/.polylith/config.edn` on first use.

That changes the intent of this issue to be unconditional but probably makes Polylith a better citizen overall.

**Comment by seancorfield** [comment]
After experimenting with running different versions of `poly` locally -- a "legacy" version and an XDG version -- I decided to make the migration work as follows:

* copy the legacy file to the new location
* read the legacy contents, add a migration comment _at the top_ and write it back out

This means that a new version of `poly` won't clobber the configuration still used by any older versions of `poly` that someone is using, but if the user goes to change the config at any point, they'll see that it was migrated to a new location, and can decide whether to edit the old config, the new config, or both.

**Comment by tengstrand** [comment]
Thanks for this @seancorfield!
