### ISSUE TITLE
Poly test should return non-zero exit code when per-project test-setup has failed

### ISSUE THREAD

**Issue by devgrapher** [polyfy/polylith#229]
**Describe the bug**
`poly test` should return non-zero exit code when per-project `:setup-fn` is given and failed (throws an exception).

**To Reproduce**
1. Have a per-project `:setup-fn` function set in `workspace.edn` and make it throw an exception.
2. Run `poly test project:{the project name}; echo "exit code: $?"` 
3. You can see a message in red `Test setup failed: *****` and `exit code: 0`

**Expected behavior**
Poly test should return non-zero exit code.

**Operating System (please complete the following information):**
 - OS: MacOS
 - Version: 12.0.1

**Versions (please complete the following information):**
 - Java: java 17.0.2 
 - Poly: 0.2.14-alpha
 - Brew: 3.3.9-80-g26694fd

**Comment by tengstrand** [comment]
Hi @Devgrapher!

This seems to work in the master branch.
Please verify this and see if you encounter any problems, otherwise I will close this issue. Thanks!

**Comment by devgrapher** [comment]
@tengstrand  Thank you for taking a look, but I'm still seeing the issue with the master branch as well.

I had this in `deps.edn`
```
           :poly {:main-opts  ["-m" "polylith.clj.core.poly-cli.core"]
                  :extra-deps {polyfy/polylith {:git/url   "https://github.com/polyfy/polylith"
                                                :sha       "adf957cc055ba1ceaca25e6119915b4d3ad77b48" ;; hash from the master
                                                :deps/root "projects/poly"}}}
```

, and ran the following
```
clj -M:poly test project:fb; echo "exit code: $?"
```

which printed messages below
```
Test setup failed: clojure.lang.ExceptionInfo: ... ;; This is intended error for this issue

Execution time: 1 minutes 0 seconds

exit code: 0
```

The exit code 1 is properly returned when it had no exception during the setup, but had an error in the test itself.
