### ISSUE TITLE
Projects tests are not run with adf957cc055ba1ceaca25e6119915b4d3ad77b48

### ISSUE THREAD

**Issue by ikitommi** [polyfy/polylith#235]
**Describe the bug**
Projects tests are not run with adf957cc055ba1ceaca25e6119915b4d3ad77b48.

```
clojure -M:poly test :all project:$PROJECT brick:-
```
... doesn't find any tests from the project-level, e.g.

```clj
Ran 0 tests containing 0 assertions.
0 failures, 0 errors.
```

with f0d38cb71e9d3f7a620a4baecb491da4aab91edd, works ok, e.g.

```clj
Ran 2 tests containing 8 assertions.
0 failures, 0 errors.

Test results: 8 passes, 0 failures, 0 errors.
```

**Comment by tengstrand** [comment]
A fix has been merged to master!

**Comment by ikitommi** [comment]
tested, works, thanks for the quick fix!
