### ISSUE TITLE
Cannot track down source of error - Don't know how to create ISeq from: java.lang.Long

### ISSUE THREAD

**Issue by vamem9z-Moses** [polyfy/polylith#254]
**Describe the bug**

Running poly info generates this error. I've been through every require in the project and I don't see anything abnormal Is there another way for me to trackdown this error?

#error {
 :cause Don't know how to create ISeq from: java.lang.Long
 :via
 [{:type java.lang.IllegalArgumentException
   :message Don't know how to create ISeq from: java.lang.Long
   :at [clojure.lang.RT seqFrom RT.java 557]}]
 :trace
 [[clojure.lang.RT seqFrom RT.java 557]
  [clojure.lang.RT seq RT.java 537]
  [clojure.lang.RT next RT.java 714]
  [clojure.core$next__5451 invokeStatic core.clj 64]
  [clojure.core$second__5457 invokeStatic core.clj 98]
  [clojure.core$second__5457 invoke core.clj 98]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$__GT_namespace invokeStatic namespaces_from_disk.clj 89]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$__GT_namespace invoke namespaces_from_disk.clj 86]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$source_namespaces_from_disk$fn__30694 invoke namespaces_from_disk.clj 94]
  [clojure.core$mapv$fn__8535 invoke core.clj 6979]
  [clojure.lang.PersistentVector reduce PersistentVector.java 343]
  [clojure.core$reduce invokeStatic core.clj 6885]
  [clojure.core$mapv invokeStatic core.clj 6970]
  [clojure.core$mapv invoke core.clj 6970]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$source_namespaces_from_disk invokeStatic namespaces_from_disk.clj 94]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$source_namespaces_from_disk invoke namespaces_from_disk.clj 93]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$namespaces_from_disk$fn__30701 invoke namespaces_from_disk.clj 102]
  [clojure.core$map$fn__5935 invoke core.clj 2770]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.RT seq RT.java 535]
  [clojure.core$seq__5467 invokeStatic core.clj 139]
  [clojure.core$apply invokeStatic core.clj 662]
  [clojure.core$mapcat invokeStatic core.clj 2800]
  [clojure.core$mapcat doInvoke core.clj 2800]
  [clojure.lang.RestFn invoke RestFn.java 423]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$namespaces_from_disk invokeStatic namespaces_from_disk.clj 102]
  [polylith.clj.core.workspace_clj.namespaces_from_disk$namespaces_from_disk invoke namespaces_from_disk.clj 99]
  [polylith.clj.core.workspace_clj.components_from_disk$read_component invokeStatic components_from_disk.clj 23]
  [polylith.clj.core.workspace_clj.components_from_disk$read_component invoke components_from_disk.clj 14]
  [polylith.clj.core.workspace_clj.components_from_disk$read_components$fn__30983 invoke components_from_disk.clj 41]
  [clojure.core$map$fn__5935 invoke core.clj 2772]
  [clojure.lang.LazySeq sval LazySeq.java 42]
  [clojure.lang.LazySeq seq LazySeq.java 51]
  [clojure.lang.Cons next Cons.java 39]
  [clojure.lang.RT length RT.java 1782]
  [clojure.lang.RT seqToArray RT.java 1723]
  [clojure.lang.LazySeq toArray LazySeq.java 132]
  [clojure.lang.RT toArray RT.java 1696]
  [clojure.core$to_array invokeStatic core.clj 346]
  [clojure.core$sort invokeStatic core.clj 3114]
  [clojure.core$sort_by invokeStatic core.clj 3120]
  [clojure.core$sort_by invokeStatic core.clj 3120]
  [clojure.core$sort_by invoke core.clj 3120]
  [polylith.clj.core.workspace_clj.components_from_disk$read_components invokeStatic components_from_disk.clj 41]
  [polylith.clj.core.workspace_clj.components_from_disk$read_components invoke components_from_disk.clj 40]
  [polylith.clj.core.workspace_clj.core$toolsdeps_ws_from_disk invokeStatic core.clj 102]
  [polylith.clj.core.workspace_clj.core$toolsdeps_ws_from_disk invoke core.clj 81]
  [polylith.clj.core.workspace_clj.core$workspace_from_disk invokeStatic core.clj 146]
  [polylith.clj.core.workspace_clj.core$workspace_from_disk invoke core.clj 139]
  [polylith.clj.core.workspace_clj.interface$workspace_from_disk invokeStatic interface.clj 8]
  [polylith.clj.core.workspace_clj.interface$workspace_from_disk invoke interface.clj 4]
  [polylith.clj.core.command.core$read_workspace invokeStatic core.clj 54]
  [polylith.clj.core.command.core$read_workspace invoke core.clj 47]
  [polylith.clj.core.command.core$workspace_reader_fn$fn__31118 invoke core.clj 61]
  [polylith.clj.core.command.core$execute invokeStatic core.clj 67]
  [polylith.clj.core.command.core$execute invoke core.clj 63]
  [polylith.clj.core.command.interface$execute_command invokeStatic interface.clj 5]
  [polylith.clj.core.command.interface$execute_command invoke interface.clj 4]
  [polylith.clj.core.poly_cli.core$_main invokeStatic core.clj 33]
  [polylith.clj.core.poly_cli.core$_main doInvoke core.clj 7]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.core$apply invokeStatic core.clj 667]
  [clojure.main$main_opt invokeStatic main.clj 514]
  [clojure.main$main_opt invoke main.clj 510]
  [clojure.main$main invokeStatic main.clj 664]
  [clojure.main$main doInvoke main.clj 616]
  [clojure.lang.RestFn applyTo RestFn.java 137]
  [clojure.lang.Var applyTo Var.java 705]
  [clojure.main main main.java 40]]

Error generated when trying to run poly info

**To Reproduce**
1. Navigate to workspace directory
2. Run poly infor
3. See error

**Expected behavior**
I expected to see the poly info layout

**Operating System (please complete the following information):**
 - OS: Fedora 36
 - Version: 5.19.16-200.fc36.x86_64

**Versions (please complete the following information):**
 - Java: openjdk 17.0.4.1 2022-08-12
 - Poly: 0.2.15-alpha
 
Thanks

**Comment by tengstrand** [comment]
I have implemented this in PR #258 @vamem9z-Moses.
Please check it out and see if it solves your problem, by using the `issue-254` branch, by using the latest SHA `81a916e262987d56e017179508e49c2f385544f7`.
