### ISSUE TITLE
Poly check fails on ifc.cljc files

### ISSUE THREAD

**Issue by dmg46664** [polyfy/polylith#259]
**Describe the bug**

poly check seems to fail for clojurec interfaces.

```
poly check
  Error 103: Missing definitions in logging-nbb-console's interface: configure-logging![args]
  Error 103: Missing definitions in logging-node's interface: configure-logging![args]
```

See expected behaviour for more.

**To Reproduce**
1. check out https://github.com/dmg46664/problems/tree/main/0006_polylith_check
2. Run `poly check`

**Expected behavior**

`logging-jvm` is pure clojure.
`logging-nbb-console` is pure clojurescript.
`logging-node` has a clojurec interface.

I would expect only `logging-nbb-console` to produce errors.

I'm aware of the following discussion, but it doesn't exactly allude to the current functionality from skimming it.
https://github.com/polyfy/polylith/discussions/168

Also it would be nice to be able to turn off validation on whitelisted clojurescript modules in the meantime.

**Screenshots**

**Workspace Attachment**
Workspace available.

**Operating System (please complete the following information):**
 - OS: MacOSX
 - Version: 12.3.1
 
**Versions (please complete the following information):**
 - Java: openjdk 17.0.2 2022-01-18 LTS
 - Poly: 0.2.15-alpha
 - Brew:3.6.8

**Comment by tengstrand** [comment]
Hi Daniel!

I'm looking into this right now and I have found the main problem.

I have created a new namespace to test against (in the issue-259 branch):
https://github.com/polyfy/polylith/blob/e9c71eba20a5b95748b61e97b3e7fc4bd25ecc7f/examples/for-test/components/company/cljc/com/for/test/company/interface.cljc#L1-L5

Right now, if we try to read this source file from disk, we get an empty result (see comment below):
https://github.com/polyfy/polylith/blob/be5876021ba62822b142d2520dddd129ffc277ef/components/workspace-clj/src/polylith/clj/core/workspace_clj/interface_defs_from_disk.clj#L48-L57

The read-file looks like this:
https://github.com/polyfy/polylith/blob/e9c71eba20a5b95748b61e97b3e7fc4bd25ecc7f/components/file/src/polylith/clj/core/file/core.clj#L108-L118

I don't know at the moment how best to solve this, so I'm going to ask for some help!

**Comment by tengstrand** [comment]
See [thread](https://clojurians.slack.com/archives/C03S1KBA2/p1678778666818049) in Slack.

**Comment by tengstrand** [comment]
Hi again!

The latest release, 0.2.17-alpha, has trouble recognising the funtions:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/631272/227786486-dce97e59-63b0-4ac8-bf5e-b2c51fcc12f0.png">

I think I have fixed the problem in the [issue-259](https://github.com/polyfy/polylith/tree/issue-259) branch:
<img width="1135" alt="image" src="https://user-images.githubusercontent.com/631272/227786286-aff3fdc3-b0bc-41ba-aa74-5f11aef7bd26.png">

It would be good if you could verify this, by running the `poly` tool agains the latest sha from the [issue-259](https://github.com/polyfy/polylith/tree/issue-259) branch (which right now is):
0b5c191645c7e3065ddb53ba81d51f945e033aaf

/Joakim

**Comment by tengstrand** [comment]
A couple of more things.

The poly tool reads `.clj` and `.cljc` files and that's why it picks up the functions in [logging-node/src/dimigi/logging/ifc.cljc](https://github.com/dmg46664/problems/blob/main/0006_polylith_check/components/logging-node/src/dimigi/logging/ifc.cljc). 

I'm also curious about how your use case looks like, when you want to have pure `.cljs` components in the workspace?

**Comment by dmg46664** [comment]
I can confirm your result that `logging-nbb-node` no longer produces errors! Thanks! 🙏 💯 

I don't think the lack of consistency across the interfaces is an issue. I hacked the example together at the time, and I can't really remember all concerns as the code base has moved on.

I can only recall some of the concerns at the time:
* `nbb` originally needed a different code base given differences in require. This was [fixed quickly once I discovered why](https://github.com/babashka/nbb/issues/256) but our work around  tech debt from prior persisted.
* `timbre` [couldn't support](https://github.com/ptaoussanis/timbre/issues/358) `nbb` nor a `poly` pipeline while still using `(meta)` to record line numbers. Was trying to work around that. Clojurescript just has a different approach to providing macros `:include-macros` https://clojurescript.org/guides/ns-forms#_sugar .

After that switching to the interceptor pattern significantly changed the way we were logging on lambdas.

Given all this, I think it's best to ignore our requirement for a pure Clojurescript component for now. If it arises again for us with clarity I will be happy to put it forward to you.

**Comment by tengstrand** [comment]
Okay, cool!

**Comment by tengstrand** [comment]
I added support to ignore warning 206 "Missing or unreadable namespace in brick/project" in the issue-259 branch.

This can be achieved by adding something like this to `workspac.edn`:
```
{ ...
 :bricks {"mybrick" {:ignore-files ["config.clj"]}}
 :projects {"myproject" {:alias "mp"
                         :ignore-files ["sub-ns/my-ns.clj"]}
  ...
}
```

Here we ignore any file with the name `config.clj` within the brick `mybrick`. We also ignore any file with the name `my_ns` (- will be replaced by _) living under a sub directory `sub_ns` in the project `myproject`.

**Comment by tengstrand** [comment]
Merged to master.

**Comment by tengstrand** [comment]
What do you think of removing the possibility to ignore files @dmg46664? 
Maybe we should just force people to add a namespace?
As it is now, we can ignore the error, but it the file is included in a test, we will get an error.

**Comment by dmg46664** [comment]
Ah, sorry I missed your March posts. 🙏 
I'll try give the new versions and features a spin, reacquaint myself and report back.

**Comment by tengstrand** [comment]
The reason you created this issue was to help users to be aware of namespaces that don't compile, instead of just getting a stack trace in a test. Then we added this warning to solve that. After that, we added the `:ignore-files` functionality, which kind of works, as long as the problematic namespace is not included in a test. If that happens, the test will not run anyway, even if we exclude it from the test run (which we don't right now). If we did, we would get a compilation error anyway. That is why it feels like we should remove the possibility to "ignore" namespaces, because it doesn't solve the original problem (and it's just about ignoring error 111). Do you have any opinion about this @dmg46664 ?

**Comment by dmg46664** [comment]
@tengstrand Your logic that the interim solution is not ideal seems sound. I'm using Kaocha for testing, so this scenario doesn't affect me anyway. Hope that helps :-)

**Comment by tengstrand** [comment]
Okay, then I will remove `:ignore-files`!

**Comment by tengstrand** [comment]
I removed the support for `:ignore-files`. The user can put clj and cljc files that don't have a valid namespace in `resources` to ignore this error. This is described in error 111 in `poly help check`.
