### ISSUE TITLE
Example in Java

### ISSUE THREAD

**Issue by tengstrand** [polyfy/polylith#278]
Create a short example that shows how Polylith code could look like if implemented in Java.

See also another example by Ethan McCue [here](https://clojurians.slack.com/archives/C013B7MQHJQ/p1673666179486829) and [here](https://clojurians.slack.com/archives/C013B7MQHJQ/p1673761666499549) (continued) in Slack with a different approach.

**Comment by tengstrand** [comment]
The example is perhaps not so useful, because we will always return the same street name, but it will show how swappable components can be implemented in Java.

**The directory/file structure**:

```
myworkspace
  components
    user
      src
        com
          mycompany
            user
              User      // the 'User' interface (Java class)
              Core      // the 'User' implementation (Java class)
    address
      src
        com
          mycompany
            address
              Address  // the 'Address' interface (Java class)
              Core     // the 'Address' implementation (Java class)
```

**address (interface)**

```
package com.mycompany.address;

import com.mycompany.address.Core;

public class Address {
    public static String street() {
        // delegates to the implementation.
        return Core.street();
    }
}
```

**address (implementation)**

```
package com.mycompany.address;

public class Core {
    public static String street () {
        // the actual implementation.
        return "My street";
    }
}
```

**user (interface)**

```
package com.mycompany.user;

import com.mycompany.user.Core;

public class User {
    public static void printStreet() {
        // delegate to the implementation.
        Core.printStreet();
    }
}
```
**user (implementation)**

```
package com.mycompany.user;

import com.mycompany.address.Address;

public class Core {
    public static void printStreet() {
        // Notice that we can access the 'address' component by using it's interface name!
        String street = Address.street();
        System.out.println("Street:" + street);
    }
}
```

If you have several components that implement the same interface, e.g. an 'admin' and a 'user' component, that both implement the 'User' interface, then the workspace file structure could look like this:

```
myworkspace
  components
    admin
      src
        com
          mycompany 
            user
              User
              Core
    user
      src
        com
          mycompany
            user
              User
              Core
```
Notice that the name of the interfaces is the same in the two components, com.mycompany.user.User. This is also how it's done in Clojure, but with the difference that in Clojure the interface will get the name com.mycompany.user.interface and be imported with the 'user' alias.

**Comment by bowbahdoe** [comment]
How would the static method approach handle a component like this? Do you have to un-opaque the object? Unsafe downcast?

```clojure
(ns company.user-service.core)

(defn create [datasource]
  {::datasource datasource})
  
(defn find-user
  [{::keys [datasource]} user-id]
  (jdbc/execute!  datasource ... user-id ...))
```

```clojure
(ns company.user-service.interface
  (:require [company.user-service.core :as core])

(defn create [datasource]
  (core/create datasource))
  
(defn find-user
  [user-service user-id]
  (core/find-user user-service user-id))
```

**Comment by tengstrand** [comment]
What do you mean with “… un-opaque the object”. Which object do you mean and what do you mean with un-opaque?

**Comment by bowbahdoe** [comment]
yeah - so in the clojure example the return value has a namespaced keyword storing the datasource. That, to me, is a "private" property I wouldn't rely on.

So the public contract of the component is

```clojure
 ;; Returns *something* that can be used with find-user
(defn create [datasource]
  (core/create datasource))

;; Takes the result of a create call as its first argument
(defn find-user
  [user-service user-id]
  (core/find-user user-service user-id))
```

and the "internals" rely on something that isn't "public"

```clojure
(defn create [datasource]
  {::datasource datasource})
  
(defn find-user
  [{::keys [datasource]} user-id]
  (jdbc/execute!  datasource ... user-id ...))
```

In clojure this is done via convention, in Java private is an actual mechanism

I don't understand how I would make a component like that without having findUser be a method on an interface or similar

so by un-opaque i mean "add datasource as a public property" and by unsafe downcast I mean

```java
User findUser(UserService userService) {
    var datasource = ((Core) userService).datasource)
}
```

**Comment by tengstrand** [comment]
What would happen if you skip some of the way you normally do things in Java and instead design your component interfaces in the same way you would have done it in Clojure? I understand it would not be idiomatic Java, but instead your components would look something like "small services" with a set of public functions. Maybe that could solve your problem?
