### ISSUE TITLE
poly check could report unnecessary component deps 

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#282]
poly check tells us if projects are missing dependencies which is important but for ongoing maintenance purposes, it would also be useful if poly check could report unnecessary dependencies in projects too. As we've refactored components lately, mostly to split them along command/query separation lines, we've had to manually try removing deps we think are no longer needing and repeatedly running check and putting things back until Polylith is happy.

**Comment by tengstrand** [comment]
I have fixed this issue and merged it to master, so please have a look.

The development project is not checked by default, but can be included by passing in `:dev`, e.g.:
  `poly check :dev`

If we are sure a component should be included in a project, we can add the `:necessary` to the project in `workspace.edn`, e.g.:
```
 :projects {"myproject" {:alias "mp"
                         :necessary ["mycomponent"]}}
            "development" {:alias "dev"}}
```

This is how it is used in the Polylith [workspace.edn](https://github.com/polyfy/polylith/blob/master/workspace.edn) file. 

Remember that the check command is also executed when running the `info` and `test` commands.

**Comment by seancorfield** [comment]
This doesn't seem to understand profiles.
```
  Warning 207: Unnecessary components were find in the api project and may be removed: http-client-hato, i18n, web-server
```
Those components are definitely required for this project: the interfaces are `http-client`, `i18n`, and `web-server`.

(but it did find several components that were genuinely not needed so that's helpful)

**Comment by seancorfield** [comment]
Other than that issue with profiles/swappable components, it seems to work well. It found a lot of components we no longer needed, since our refactoring, so that saved me a lot of manual work. Thanks.

**Comment by tengstrand** [comment]
I think I have fixed the problem now, so please have a look again.

**Comment by seancorfield** [comment]
Confirmed: this no longer complains about the swappable components! Thank you!

**Comment by tengstrand** [comment]
Sounds good!
