### ISSUE TITLE
:deps/manifest ignored

### ISSUE THREAD

**Issue by p14n** [polyfy/polylith#302]
**Describe the bug**
Poly does not honour the :deps/manifest option, resulting in

```
Couldn't resolve libraries for the development project: clojure.lang.ExceptionInfo: Manifest file not found for io.github.ring-clojure/ring in coordinate #:git{:sha "1db1b306ce8ec4db2f17a8cb0c9c98fe7f90146f", :url "https://github.com/ring-clojure/ring.git"} {:lib io.github.ring-clojure/ring, :coord #:git{:sha "1db1b306ce8ec4db2f17a8cb0c9c98fe7f90146f", :url "https://github.com/ring-clojure/ring.git"}}
Manifest file not found for io.github.ring-clojure/ring in coordinate #:git{:sha "1db1b306ce8ec4db2f17a8cb0c9c98fe7f90146f", :url "https://github.com/ring-clojure/ring.git"}
```

**To Reproduce**
1. Check out https://github.com/p14n/poly-deps-manifest
2. Run `clojure -Mpoly test :dev`

**Expected behavior**
Tools deps will honour and resolve this dependency.

**Operating System (please complete the following information):**
 - OS: MacOS
 - Version: 13.3.1

**Versions (please complete the following information):**
 - Java: openjdk 11.0.18 2023-01-17 LTS
 - Poly: 0.2.17-alpha

**Additional context**
I will be submitting a PR to resolve this

**Comment by tengstrand** [comment]
Thanks for fixing this!
