### ISSUE TITLE
Outdated examples/docs

### ISSUE THREAD

**Issue by ignorabilis** [polyfy/polylith#304]
https://github.com/seancorfield/build-clj has been archived and the uberjar functionality exists under `clojure.tools.build.api/uber`.

Additionally the tutorial is missing the step to add tools.deps to the project (`command-line`), which makes following the tutorial a bit unintuitive (the build fails). Images attached:
![image](https://user-images.githubusercontent.com/13527066/234910584-18e423f7-16e2-429a-9aef-b58a98b30369.png)
![image](https://user-images.githubusercontent.com/13527066/234912232-89813b74-54c0-4335-aab7-37c186297922.png)
![image](https://user-images.githubusercontent.com/13527066/234911132-c88c7b81-7fbf-443d-9306-936acca45f21.png)

Also `tools.deps.alpha` is still being used in the tutorial, but the file itself has been updated (thus causing yet another set of errors):
![image](https://user-images.githubusercontent.com/13527066/234913248-f49fa463-ad41-41cb-8fe4-d53e6d49d438.png)
![image](https://user-images.githubusercontent.com/13527066/234913525-2c1e3fa9-9a8e-49ab-9056-f2a13ffdd933.png)

I hope that helps.

**Comment by ignorabilis** [comment]
by the way `poly` adds the alpha version of tools.deps (I believe I'm using the latest one, 0.2.17, which is from December 22)

**Comment by tengstrand** [comment]
Thanks for reporting this, and nice screen shots! 
Will have a look, and include this in the next release.

**Comment by ignorabilis** [comment]
> Thanks for reporting this, and nice screen shots! Will have a look, and include this in the next release.

awesome @tengstrand !

**Comment by seancorfield** [comment]
The version of `build-clj` is very old. I just submitted a CR to the docs to update that to `v0.9.2` which should fix the `clojure.tools.deps` (not `.alpha`) issue.

Polylith should **stop adding the `t.d.a.` dep** -- it hasn't been needed as a default dependency (ever?) in new projects.

**Comment by ignorabilis** [comment]
thanks @seancorfield ; I was suspecting that `t.d.a.` was never needed too, judging by the examples commits - but couldn't be 100% sure.

**Comment by seancorfield** [comment]
#312 deals with the `build-clj` -> `tools.build` changes and I have a branch in my own repo up for that: https://github.com/polyfy/polylith/compare/master...seancorfield:polylith:issue-312

I believe @tengstrand is addressing the unnecessary `tools.deps` additions in another ticket.

**Comment by tengstrand** [comment]
I have merged this branch to master now, and I will update the release branch in gitbook, which will be released together with 0.2.18.

**Comment by tengstrand** [comment]
See also [this](https://clojurians.slack.com/archives/C013B7MQHJQ/p1688691212621849) thread in Slack.

**Comment by tengstrand** [comment]
I believe all reported issues should be fixed by now. Can you please verify that [here](https://cljdoc.org/d/polylith/clj-poly/0.2.18-SNAPSHOT/doc/readme) @ignorabilis ?
