### ISSUE TITLE
Update Edamame dependency to 1.4.25

### ISSUE THREAD

**Issue by seancorfield** [polyfy/polylith#432]
Polylith currently uses `borkdude/edamame 1.3.23` but that cannot read files containing the new Clojure 1.12 Alpha 7 param tags type hint (e.g., `^[String]`). `borkdude/edamame 1.4.25` supports this (it was released last night after Alpha 7 started to be tested).

**Comment by tengstrand** [comment]
Fixed in 0.2.19-SNAPSHOT #7.
