### ISSUE TITLE
brew upgrade poly currently stuck on 0.2.18 version

### ISSUE THREAD

**Issue by velios** [polyfy/polylith#462]
Hello. Thx for great approach and tool first of all.

`brew install polyfy/polylith/poly` currently stuck on version `0.2.18` when the last version `0.2.19` like 4 month. 

Perhaps it is worth increasing the recommended version to the latest or are there reasons why this should not be done?

**Comment by furkan3ayraktar** [comment]
You are right. It's not connected to the CI and needs to be published manually, which is why we forgot to release it. I did release it now. If you run `brew upgrade polyfy/polylith/poly`, it should upgrade it to `0.2.19`.

**Comment by velios** [comment]
Thank you very much. Now it works as expected.
