### ISSUE TITLE
Requiring multiple non-interface namespaces from another component throws java.lang.ClassCastException

### ISSUE THREAD

**Issue by eval-on-point** [polyfy/polylith#504]
**Describe the bug**
Requiring multiple non-interface namespaces from another component throws java.lang.ClassCastException. 

**To Reproduce**
[This example repository](https://github.com/eval-on-point/polylith-bug) shows a minimal example workspace that reproduces the error with instructions.

**Expected behavior**
Instead of a stacktrace, I expect `poly` to give me multiple illegal dependency errors or otherwise not throw an error.

**Additional context**
Found while trying to reproduce the error described in [this Slack thread](https://clojurians.slack.com/archives/C013B7MQHJQ/p1723144500411309). This error does not seem to appear on version 0.2.19.

**Comment by hiredman** [comment]
https://github.com/polyfy/polylith/blob/adfcaa2789acad5d29a5d47ffeaeefd19672250a/components/deps/src/polylith/clj/core/deps/brick_deps/core.clj#L58 looks like missing map of :to-brick-id or something similar?

**Comment by eval-on-point** [comment]
Seems like it may not be reproducible on some systems (see [this message in Slack](https://clojurians.slack.com/archives/C013B7MQHJQ/p1723222367064909?thread_ts=1723144500.411309&cid=C013B7MQHJQ)). I've added a nix flake to the repo. This flake creates a devenv shell that reproduces the issue for me.

**Comment by tengstrand** [comment]
Will have a look.

**Comment by tengstrand** [comment]
I can't reproduce the error:

```
(comment
  (def source :src)
  (def interface-ns "top.")
  (def deps [{:from-type "component", :from-ns "interface", :to-type "library", :to-brick-id "component-two", :to-namespace "core"} 
             {:from-type "component", :from-ns "core", :to-type "library", :to-brick-id "component-two", :to-namespace "core"}])
  (filter #(illegal-dep? % interface-ns source) deps)
  #__)
```

The other two should do `map :to-brick-id` but not `illegal-deps`. 
I can't see what's wrong here, but maybe you can guide me.

**Comment by tengstrand** [comment]
Maybe you could clone the polylith repo and then point to it in an alias, which is described [here](https://cljdoc.org/d/polylith/clj-poly/0.3.21-SNAPSHOT/doc/developing-poly#_referencing_a_local_poly).
If the problem remains, then you have access to the polylith source code, so you can add print statements and the like, as a way to find what the problem is.

**Comment by hiredman** [comment]
I haven't repo'ed the error, just looking at the code
https://github.com/polyfy/polylith/blob/adfcaa2789acad5d29a5d47ffeaeefd19672250a/components/deps/src/polylith/clj/core/deps/brick_deps/core.clj#L51-L61

deps on line 52 is a sequence of maps, interface-deps (line 53) is a sequence of whatever :to-brick-id is (presumably not a map), same for base-deps(line 56), but illegal-deps (line 58) remains a sequence of maps. so interface-deps sorts fine, base-deps sorts fine, but illegal-deps throws an error when trying to sort it (when it is non-empty).

**Comment by tengstrand** [comment]
Okay, thanks, now I get it! Will fix!

**Comment by eval-on-point** [comment]
Confirming that 2fca38b fixes the issue in both of my repos.

**Comment by tengstrand** [comment]
Thanks for setting up that extra repo!
