### ISSUE TITLE
Polylith should not put data in the root of deps.edn

### ISSUE THREAD

**Issue by puredanger** [polyfy/polylith#65]
Polylith puts data under the `:polylith` key at the root of deps.edn. This is a bad idea as tools.deps/clj make no promises about how data at the root is merged/combined or whether it will be allowed at all in the future. **That is, this usage may be disallowed and/or broken at any time in the future, without warning.**

Two alternatives:

1) Make your own edn configuration file independent from deps.edn.
2) Store data under an alias. The deps.edn allows arbitrary data to be stored under the `:aliases` key. Alias data can be retrieved from the runtime basis. Currently, clj injects the basis file path via the `clojure.basis` system property (the basis is a superset of the merged deps.edn file - whether custom root keys are included in the basis is a matter of debate but may similar to above, be disallowed). In the future, we think it's likely to have an api for accessing alias data in Clojure core.

**Comment by tengstrand** [comment]
Hi Alex!

Thanks for trying out Polylith and that you make us aware of this problem!
We will go for option 1, and start working on this as soon as possible.

I'm just curious, but I guess there are technical reasons why you don't follow the principle that Rich often advocates, that it should be possible to add keys to a map without breaking anything.

/Joakim

**Comment by puredanger** [comment]
The top-level keys of deps.edn should be considered a reserved space - we don't want deps.edn to become a dumping ground for everyone's project data, as over time that will become intractable.
