### ISSUE TITLE
Possible readme instruction issue

### ISSUE THREAD

**Issue by bpringe** [polyfy/polylith#85]
Under the section "Create a build script for `user-service`,"  there's a line that says to open the _interface_ namespace of the user-remote component and load this file in order to replace the user-remote implementation: "This will replace the `user` implementation with the `user-remote` component."

I found that this didn't replace the implementation, which makes sense to me, because that's the interface namespace, not the implementation namespace, that was just loaded. In order to make the next steps in the readme work as stated, I had to open the user-remote _implementation_ namespace and load this file. This also makes sense to me because to replace an implementation, the implementation namespace with desired code should be loaded.

It could also be that I'm misunderstanding something here, but this is how it works with my editor.

**Comment by tengstrand** [comment]
You understood right!
