### ISSUE TITLE
Change character used to represent src/resource/test/execute flags in info command

### ISSUE THREAD

**Issue by futuro** [polyfy/polylith#90]
**Is your feature request related to a problem? Please describe.**
Remembering which column in the info command output represents the source/resource/test/execute-test is tricky, and it'd be nice if it was self-evident.

**Describe the solution you'd like**
In the output of the `info` command, make the following changes:

- wherever we're showing that a `src` directory is included, use the `s` character instead of `x`; mnemonic `s`rc directory 
- wherever we're showing that a `resource` directory is included, use the `r` character instead of `x`; mnemonic `r`esource directory
- wherever we're showing that a `test` directory is included, use the `t` character instead of `x`; mnemonic `t`est directory
- wherever we're showing that the tests would be executed, continue using the `x` character; mnemonic e`x`ecute, and it matches the existing unix file permission flag of `x` for executable

**Describe alternatives you've considered**
I'd initially tried to memorize the positions, but didn't come to much success. I also think being explicit about the type of thing we're showing is better ergonomics and removes any ambiguity for future users.

This also helps in the case that you call `poly info :resources`, since in the current system you have to remember that the second `x` is for tests without `:resources` passed in, and is for resources when you pass in `:resources`.

**Additional context**
I'm game to work on this in my free time if you can help point me in the right direction. I started looking into this today but got a bit lost among the `project_table` and `text-table` namespaces.

**Comment by tengstrand** [comment]
I like the idea. I will play around with it when I have time!

**Comment by tengstrand** [comment]
I have implemented this in the `issue-66` branch. This is how it looks like in the [realworld](https://github.com/furkan3ayraktar/clojure-polylith-realworld-example-app/tree/polylith-issue-66) example app:
<img width="335" alt="info-status-flags" src="https://user-images.githubusercontent.com/631272/125156008-88ea4b00-e163-11eb-9a66-16ca87abad72.png">

...and with the resources flag included:
<img width="346" alt="info-status-flags-resources" src="https://user-images.githubusercontent.com/631272/125156126-2d6c8d00-e164-11eb-9ca0-056d9c0a3745.png">

This was a great change in my mind, so thanks again for the idea!

This will be available to everyone when the `issue-66` branch is merged into `master`.

**Comment by furkan3ayraktar** [comment]
Fixed in #94

**Comment by futuro** [comment]
This looks wonderful, thank you @furkan3ayraktar!

**Comment by futuro** [comment]
Also thank you @tengstrand!

**Comment by tengstrand** [comment]
I should thank you also @futuro, because it was a really good idea you came up with!
