### ISSUE TITLE
Question: recommended way to write tests components sharing common interface

### ISSUE THREAD

**Issue by volisoft** [polyfy/polylith#93]
**Describe the bug**
_Note: this is not a bug, but a request for clarification (didn't find appropriate template)._

What should be a test setup for two or more components sharing the same interface?
The assumption is that the tests are written against interface, not implementation. This goal is to re-use the test suite for both components.

Given components A and B with the same interface, potential options are:
- Place the tests in A's test directory and use them to test both A and B
- Create a component C containing only test directory with dependencies on A and B
- Create a test project to test both components

**What is the recommended way?**

**To Reproduce**
1. Create components A and B sharing same interface
2. Think about where to put the interface (contract) tests

**Expected behavior**
Polylith architecture has a nice solution for this

**Comment by tengstrand** [comment]
Hi @volisoft ,

Let's say we have two components `a1` and `a2` which both implement the interface `a`.
To test both through the same interface, we can create the component `a-tester` that has code in the `test` directory that tests against the interface `a`. Then we can create a project `p1` that includes both `a1` and `a-tester`.
To test `a2` we create the project `p2` that includes both `a2` and `a-tester`.

In Polylith a project can only contain one component per interface, so in this case we can only pick `a1` or `a2` for each project. To run tests, we need a project to put the code in (brick tests are always executed from a project) which is the reason we had to create `p1` and `p2`.

Hope this answered your question,
/Joakim

**Comment by volisoft** [comment]
Hi Joakim,

Thank you for the prompt response. To summarize, this setup requires a test suite to be a separate component. This makes sense, and I think it delineates the test component's responsibilities perfectly.
Thank you for clarifications!

**Comment by tengstrand** [comment]
Sounds good!
